<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Migrations\Migration;

/**
 * SEO meta for the other 23 city pages (Gurugram was done in
 * 2026_09_25_150000). Normally edited in Super Admin; set here so the change
 * is deployed, recorded and reversible.
 *
 * The titles ran to 70–116 characters, ended in the misspelt "NxtTutors",
 * and Chandigarh's was a sentence fragment. The descriptions were about
 * 1,000 characters each, of which Google shows ~155. New titles are
 * "Home Tutors in <City> – CBSE, ICSE, IB, JEE | NXTutors" (≤65 characters)
 * and descriptions name the city and state in ~140 characters.
 *
 * down() puts back exactly what was live on 25 Sep 2026 (read from the
 * rendered pages).
 */
return new class extends Migration
{
    /** slug => [meta_title, meta_desc] */
    private const NEW = [
        'jaipur' => ['Home Tutors in Jaipur – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Jaipur, Rajasthan for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'delhi-ncr' => ['Home Tutors in Delhi NCR – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Delhi, Noida, Greater Noida and Ghaziabad for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'mumbai' => ['Home Tutors in Mumbai – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Mumbai, Maharashtra for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'bengaluru' => ['Home Tutors in Bengaluru (Bangalore) – CBSE, ICSE, IB | NXTutors', 'Verified home and online tutors in Bengaluru, Karnataka for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'hyderabad' => ['Home Tutors in Hyderabad – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Hyderabad, Telangana for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'chennai' => ['Home Tutors in Chennai – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Chennai, Tamil Nadu for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'pune' => ['Home Tutors in Pune – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Pune, Maharashtra for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'ahmedabad' => ['Home Tutors in Ahmedabad – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Ahmedabad, Gujarat for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'kolkata' => ['Home Tutors in Kolkata – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Kolkata, West Bengal for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'chandigarh' => ['Home Tutors in Chandigarh – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Chandigarh, Mohali and Panchkula for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'lucknow' => ['Home Tutors in Lucknow – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Lucknow, Uttar Pradesh for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'indore' => ['Home Tutors in Indore – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Indore, Madhya Pradesh for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'bhopal' => ['Home Tutors in Bhopal – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Bhopal, Madhya Pradesh for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'nagpur' => ['Home Tutors in Nagpur – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Nagpur, Maharashtra for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'kochi' => ['Home Tutors in Kochi – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Kochi, Kerala for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'surat' => ['Home Tutors in Surat – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Surat, Gujarat for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'thiruvananthapuram' => ['Home Tutors in Thiruvananthapuram – CBSE, ICSE, IB | NXTutors', 'Verified home and online tutors in Thiruvananthapuram, Kerala for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'guwahati' => ['Home Tutors in Guwahati – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Guwahati, Assam for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'patna' => ['Home Tutors in Patna – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Patna, Bihar for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'coimbatore' => ['Home Tutors in Coimbatore – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Coimbatore, Tamil Nadu for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'ranchi' => ['Home Tutors in Ranchi – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Ranchi, Jharkhand for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'tata' => ['Home Tutors in Jamshedpur – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Jamshedpur, Jharkhand for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
        'faridabad' => ['Home Tutors in Faridabad – CBSE, ICSE, IB, JEE | NXTutors', 'Verified home and online tutors in Faridabad, Haryana for CBSE, ICSE, IB, IGCSE, JEE and NEET. Get 2–3 matched tutors and a free demo class.'],
    ];

    private const OLD = [
        'jaipur' => ['Best Home & Online Tutors in Jaipur | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for experienced home tutors and online tutors in Jaipur? NxtTutors connects students with verified, highly qualified educators for personalized one-on-one learning across CBSE, ICSE, ISC, IB, IGCSE, and State Boards. Get expert academic support for Mathematics, Science, English, Commerce, and other subjects, along with dedicated preparation for JEE, NEET, and board examinations. Our AI-powered tutor matching system helps students find the right tutor based on their academic goals, learning style, schedule, and budget. Whether you need home tuition, online classes, or hybrid learning in Jaipur, NxtTutors provides flexible, result-oriented education designed to improve concept clarity, confidence, and overall academic performance.'],
        'delhi-ncr' => ['Best Home & Online Tutors in Delhi NCR | CBSE, ICSE, IB Coaching | NxtTutors', 'Searching for expert home tutors and online tutors in Delhi NCR? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curriculums. Our platform offers subject-specific guidance in Mathematics, Science, English, Commerce, and Humanities, along with dedicated coaching for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching system, NxtTutors recommends the right tutor based on a student\'s academic goals, learning style, preferred schedule, and budget. Whether you need home tuition, online classes, or hybrid learning solutions across Delhi, Noida, Gurugram, Ghaziabad, Faridabad, or Greater Noida, NxtTutors delivers flexible, result-oriented education that strengthens concepts, improves confidence, and helps students achieve long-term academic success.'],
        'mumbai' => ['Best Home & Online Tutors in Mumbai | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for trusted home tutors and online tutors in Mumbai? NxtTutors helps students connect with experienced and verified educators who deliver personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board students. From primary classes to senior secondary education, our tutors provide expert guidance in Mathematics, Science, English, Commerce, Humanities, and specialized subjects. We also support students preparing for JEE, NEET, Olympiads, and board examinations with structured learning plans and targeted academic strategies. Using an AI-powered tutor matching system, NxtTutors recommends the most suitable tutor based on a student\'s learning style, academic goals, schedule, and preferences. Whether you need home tuition, online classes, or hybrid learning across Mumbai, NxtTutors offers flexible, result-oriented education that builds confidence, strengthens concepts, and helps students achieve consistent academic success.'],
        'bengaluru' => ['Best Home & Online Tutors in Bengaluru | CBSE, ICSE, IB & IGCSE | NxtTutors', 'Looking for experienced home tutors and online tutors in Bengaluru? NxtTutors helps students connect with qualified and verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curriculums. Bengaluru\'s growing international education ecosystem has increased the demand for customized academic support, and NxtTutors offers flexible learning solutions designed for modern learners. Students can receive expert guidance in Mathematics, Science, English, Coding, Commerce, and other subjects, along with structured preparation for JEE, NEET, Olympiads, and board examinations. Our AI-powered tutor matching platform recommends the right tutor based on academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Bengaluru, NxtTutors provides engaging, result-oriented education that improves conceptual understanding, builds confidence, and helps students achieve long-term academic success while adapting to today\'s competitive educational environment.'],
        'hyderabad' => ['Best Home & Online Tutors in Hyderabad | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for trusted home tutors and online tutors in Hyderabad? NxtTutors connects students with experienced and verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Hyderabad is one of India\'s leading education and technology hubs, creating strong demand for quality academic support and competitive exam preparation. Our tutors offer expert guidance in Mathematics, Science, English, Commerce, Coding, and other subjects, along with focused preparation for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching platform, NxtTutors recommends the ideal tutor based on a student\'s learning style, academic goals, schedule, and individual requirements. Whether you need home tuition, online classes, or hybrid learning across Hyderabad, NxtTutors provides flexible, result-driven education that strengthens concepts, boosts confidence, and helps students achieve outstanding academic results.'],
        'chennai' => ['Best Home & Online Tutors in Chennai | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for reliable home tutors and online tutors in Chennai? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Chennai is known for its strong academic culture and quality-focused approach to education, making personalized tutoring an essential part of student success. Our expert tutors offer subject-specific guidance in Mathematics, Science, English, Commerce, Coding, and Humanities, along with strategic preparation for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching platform, NxtTutors identifies the right tutor based on a student\'s learning style, academic goals, schedule, and individual needs. Whether you need home tuition, online classes, or hybrid learning across Chennai, NxtTutors delivers flexible, engaging, and result-oriented education that strengthens conceptual understanding, improves performance, and supports long-term academic achievement.'],
        'pune' => ['Best Home & Online Tutors in Pune | CBSE, ICSE, IB & IGCSE | NxtTutors', 'Loking for experienced home tutors and online tutors in Pune? NxtTutors helps students connect with verified and highly qualified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. As one of India\'s leading educational destinations, Pune has a growing community of students preparing for board exams, competitive entrance tests, and international academic programs. Our tutors provide expert guidance in Mathematics, Science, English, Commerce, Coding, and other key subjects, along with focused preparation for JEE, NEET, Olympiads, and scholarship examinations. Using an AI-powered tutor matching platform, NxtTutors recommends the most suitable tutor based on each student\'s academic goals, learning preferences, schedule, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Pune, NxtTutors delivers flexible, engaging, and result-oriented education that improves conceptual understanding, builds confidence, and supports long-term academic excellence.'],
        'ahmedabad' => ['Best Home & Online Tutors in Ahmedabad | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for expert home tutors and online tutors in Ahmedabad? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Ahmedabad has a strong academic culture with increasing demand for quality tutoring, competitive exam preparation, and skill-based learning. Our tutors offer specialized guidance in Mathematics, Science, English, Commerce, Coding, and other core subjects, along with focused preparation for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching platform, NxtTutors recommends the most suitable tutor based on a student\'s academic goals, learning preferences, schedule, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Ahmedabad, NxtTutors provides flexible, personalized, and result-oriented education that strengthens concepts, improves performance, and helps students achieve long-term academic success.'],
        'kolkata' => ['Best Home & Online Tutors in Kolkata | CBSE, ICSE, IB Coaching | NxtTutors', 'Looking for experienced home tutors and online tutors in Kolkata? NxtTutors connects students with verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Kolkata has a strong educational foundation with increasing demand for flexible hybrid learning that combines online and offline academic support. Our expert tutors offer guidance in Mathematics, Science, English, Commerce, Coding, and other core subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Through an AI-powered tutor matching platform, NxtTutors identifies the most suitable tutor based on a student\'s academic goals, learning style, schedule, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Kolkata, NxtTutors delivers structured, personalized, and result-oriented education that improves conceptual understanding, builds confidence, and supports long-term academic success.'],
        'chandigarh' => ['Chandigarh is a quality-focused education city with strong demand for personalized tutoring and academic excellence.', 'Looking for expert home tutors and online tutors in Chandigarh? NxtTutors helps students connect with verified and highly qualified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Chandigarh is known for its strong academic environment, high parental involvement, and increasing demand for quality private tuition. Our tutors offer specialized guidance in Mathematics, Science, English, Commerce, Coding, and other core subjects while also supporting students preparing for JEE, NEET, Olympiads, and board examinations. Through an AI-powered tutor matching platform, NxtTutors identifies the ideal tutor based on each student\'s academic goals, learning pace, schedule, and educational needs. Whether you need home tuition, online classes, or hybrid learning across Chandigarh, NxtTutors provides flexible, personalized, and outcome-driven education that strengthens conceptual understanding, improves academic performance, and helps students achieve long-term success.'],
        'lucknow' => ['Best Home & Online Tutors in Lucknow | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Lucknow? NxtTutors helps students connect with experienced and verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Lucknow has a rapidly expanding student community with growing awareness of quality education, making personalized tutoring an important part of academic success. Our tutors offer expert guidance in Mathematics, Science, English, Commerce, Social Studies, and other core subjects, along with structured preparation for JEE, NEET, Olympiads, and board examinations. Through an AI-powered tutor matching platform, NxtTutors recommends the ideal tutor based on each student\'s academic goals, learning pace, schedule, and educational requirements. Whether you need home tuition, online classes, or hybrid learning across Lucknow, NxtTutors provides flexible, student-focused, and result-driven education that strengthens conceptual understanding, improves academic performance, and builds long-term confidence for future success.'],
        'indore' => ['Best Home & Online Tutors in Indore | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for expert home tutors and online tutors in Indore? NxtTutors connects students with experienced and verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Indore has emerged as one of India\'s fastest-growing education centres, with increasing demand for academic excellence, competitive exam preparation, and skill-based learning. Our tutors offer dedicated support in Mathematics, Science, English, Commerce, Coding, and other core subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching platform, NxtTutors recommends the right tutor based on each student\'s academic goals, learning style, schedule, and educational requirements. Whether you need home tuition, online classes, or hybrid learning across Indore, NxtTutors provides flexible, personalized, and result-driven education that improves conceptual understanding, boosts confidence, and supports long-term academic achievement.'],
        'bhopal' => ['Best Home & Online Tutors in Bhopal | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Bhopal? NxtTutors connects students with experienced and verified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Bhopal has a steadily growing academic ecosystem where students and parents are increasingly adopting home tuition and online learning to achieve better educational outcomes. Our tutors offer expert guidance in Mathematics, Science, English, Commerce, Social Studies, Coding, and other key subjects, along with focused preparation for JEE, NEET, Olympiads, and board examinations. Using an AI-powered tutor matching platform, NxtTutors recommends the most suitable tutor based on a student\'s academic goals, learning preferences, schedule, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Bhopal, NxtTutors delivers flexible, personalized, and result-oriented education that strengthens concepts, improves confidence, and helps students achieve long-term academic success.'],
        'nagpur' => ['Best Home & Online Tutors in Nagpur | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for expert home tutors and online tutors in Nagpur? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Nagpur is steadily becoming an important educational destination with increasing demand for quality academic support, board exam preparation, and competitive entrance coaching. Our tutors provide specialized guidance in Mathematics, Science, English, Commerce, Coding, and other essential subjects while supporting students preparing for JEE, NEET, Olympiads, and scholarship examinations. Through an AI-powered tutor matching platform, NxtTutors identifies the most suitable tutor based on each student\'s academic goals, learning preferences, schedule, and educational requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Nagpur, NxtTutors delivers flexible, affordable, and result-oriented education that strengthens concepts, improves performance, and helps students build a strong foundation for long-term academic success.'],
        'kochi' => ['Best Home & Online Tutors in Kochi | CBSE, ICSE, IB & IGCSE | NxtTutors', 'Looking for experienced home tutors and online tutors in Kochi? NxtTutors connects students with verified and highly qualified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Kochi has emerged as a globally connected education destination with growing adoption of international school boards and modern learning approaches. Our expert tutors provide customized support in Mathematics, Science, English, Commerce, Coding, and other essential subjects while helping students prepare for board examinations, Olympiads, and future academic opportunities. Through an AI-powered tutor matching platform, NxtTutors identifies the ideal tutor based on each student\'s academic goals, learning preferences, schedule, and educational requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Kochi, NxtTutors delivers flexible, technology-enabled, and result-oriented education that strengthens concepts, improves confidence, and prepares students for long-term academic success in an increasingly global learning environment.'],
        'surat' => ['Best Home & Online Tutors in Surat | CBSE, ICSE, IB & IGCSE | NxtTutors', 'Looking for expert home tutors and online tutors in Surat? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. As one of India\'s fastest-growing economic cities, Surat has witnessed a significant rise in demand for quality education, international school programs, and personalized academic support. Our tutors provide expert guidance in Mathematics, Science, English, Commerce, Coding, and other essential subjects, along with structured preparation for JEE, NEET, Olympiads, and board examinations. Through NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Surat, NxtTutors delivers flexible, technology-enabled, and result-oriented education that strengthens concepts, improves confidence, and helps students achieve long-term academic success in a competitive learning environment.'],
        'thiruvananthapuram' => ['Best Home & Online Tutors in Thiruvananthapuram | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Thiruvananthapuram? NxtTutors connects students with verified and highly qualified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Known for its high literacy rate and strong academic culture, Thiruvananthapuram has a growing demand for quality home tuition and technology-enabled learning solutions. Our expert tutors provide customized support in Mathematics, Science, English, Commerce, Coding, and other key subjects while helping students excel in board examinations, Olympiads, and future academic goals. Using an AI-powered tutor matching platform, NxtTutors identifies the most suitable tutor based on each student\'s learning style, academic objectives, schedule, and educational requirements. Whether you need home tuition, online classes, or hybrid learning across Thiruvananthapuram, NxtTutors delivers flexible, personalized, and outcome-focused education that strengthens concepts, improves confidence, and supports long-term academic success.'],
        'guwahati' => ['Best Home & Online Tutors in Guwahati | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Guwahati? NxtTutors connects students with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. As the educational gateway to Northeast India, Guwahati is witnessing growing demand for quality academic support, modern learning methods, and competitive exam preparation. Our tutors provide expert guidance in Mathematics, Science, English, Commerce, Coding, and other essential subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Using NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Guwahati, NxtTutors delivers flexible, personalized, and result-oriented education that strengthens concepts, improves confidence, and helps students achieve long-term academic success in a fast-evolving educational landscape.'],
        'patna' => ['Best Home & Online Tutors in Patna | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for experienced home tutors and online tutors in Patna? NxtTutors connects students with verified and highly qualified educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Patna has a strong academic ecosystem with a large student population focused on competitive exams, board examinations, and career-oriented education. Our tutors offer expert guidance in Mathematics, Science, English, Commerce, Social Studies, Coding, and other core subjects while supporting preparation for JEE, NEET, Olympiads, and scholarship examinations. Through NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Patna, NxtTutors delivers structured, personalized, and result-driven education that strengthens concepts, builds confidence, and helps students achieve long-term academic success.'],
        'coimbatore' => ['Best Home & Online Tutors in Coimbatore | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for expert home tutors and online tutors in Coimbatore? NxtTutors connects students with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Coimbatore is steadily emerging as a high-quality education destination with increasing interest in STEM education, skill-based learning, and academic excellence. Our tutors provide specialized support in Mathematics, Science, English, Coding, Commerce, and other core subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Using NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Coimbatore, NxtTutors delivers flexible, personalized, and outcome-driven education that strengthens concepts, builds confidence, and prepares students for long-term academic success in a technology-driven world.'],
        'ranchi' => ['Best Home & Online Tutors in Ranchi | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Ranchi? NxtTutors helps students connect with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Ranchi is steadily emerging as an important educational destination with growing demand for quality academic support, home tuition, and competitive exam preparation. Our tutors provide expert guidance in Mathematics, Science, English, Commerce, Social Studies, Coding, and other essential subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Through NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Ranchi, NxtTutors delivers flexible, personalized, and result-oriented education that strengthens concepts, improves confidence, and helps students achieve long-term academic success.'],
        'tata' => ['Best Home & Online Tutors in Jamshedpur | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Jamshedpur? NxtTutors connects students with verified and experienced educators who provide personalized one-on-one learning for CBSE, ICSE, ISC, IB, IGCSE, and State Board curricula. Jamshedpur has a strong educational foundation supported by technology-driven families and a growing demand for quality academic guidance. Our tutors provide expert support in Mathematics, Science, English, Commerce, Coding, and other key subjects while helping students prepare for JEE, NEET, Olympiads, and board examinations. Using NxtTutors\' AI-powered tutor matching platform, students are paired with tutors based on their academic goals, learning preferences, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Jamshedpur, NxtTutors delivers flexible, personalized, and result-oriented education that strengthens concepts, builds confidence, and helps students achieve long-term academic success.'],
        'faridabad' => ['Best Home & Online Tutors in Faridabad | CBSE, ICSE & IB Tutors | NxtTutors', 'Looking for trusted home tutors and online tutors in Faridabad? NxtTutors helps students connect with verified, experienced, and highly qualified educators for personalized one-on-one learning. Faridabad has become an important educational destination within the NCR region, with increasing demand from families seeking quality academic support beyond traditional classroom learning. Our tutors provide expert guidance for CBSE, ICSE, ISC, IB, IGCSE, and State Board students across subjects including Mathematics, Science, English, Commerce, Coding, and competitive exam preparation for JEE, NEET, Olympiads, and board examinations. NxtTutors uses an AI-powered tutor matching system to pair students with the right tutor based on academic goals, learning styles, schedules, and individual requirements. Whether you need home tuition, online classes, or hybrid learning anywhere in Faridabad, NxtTutors delivers flexible, personalized, and result-driven education that strengthens concepts, improves performance, and builds long-term academic confidence.'],
    ];

    public function up(): void
    {
        $this->apply(self::NEW);
    }

    public function down(): void
    {
        $this->apply(self::OLD);
    }

    private function apply(array $rows): void
    {
        foreach ($rows as $slug => [$title, $desc]) {
            DB::table('city_managment')->where('slug', $slug)->update([
                'meta_title' => $title,
                'meta_desc' => $desc,
            ]);
        }
    }
};
