<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Live is not Verified (owner decision, 3 Oct 2026). While hiring fast, a new
 * tutor goes live at once and the Verified badge waits for the team's ID
 * check (config tutors.publish_before_review, App\Support\TutorBadge).
 *
 *  - register.id_verified_at (nullable timestamp): set by the admin's Approve;
 *    the Verified badge needs it.
 *  - register.id_verified_by (nullable VARCHAR(64)): who approved.
 *  - register.review_notified_at (nullable timestamp): the one "New tutor to
 *    check" email has been sent (App\Services\TutorIntake).
 *
 * Backfill, so today's badges do not disappear and nobody gets an email for
 * an old account:
 *  - id_verified_at = now for live ('t') real tutors: not samples, and either
 *    one of the confirmed real tutors (config tutors.real_user_ids) or an
 *    account with a phone on record. Profiles generated by the admin's AI tool
 *    have no phone and were never ID-checked, so they get no badge.
 *  - review_notified_at = now for every existing tutor row.
 *
 * down() drops the three columns.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (! Schema::hasTable('register')) {
            return; // pre-migration table; absent in fresh test databases
        }

        $add = array_values(array_filter(
            ['id_verified_at', 'id_verified_by', 'review_notified_at'],
            fn ($c) => ! Schema::hasColumn('register', $c),
        ));
        if ($add === []) {
            return;
        }

        Schema::table('register', function (Blueprint $t) use ($add) {
            if (in_array('id_verified_at', $add, true)) {
                $t->timestamp('id_verified_at')->nullable();
            }
            if (in_array('id_verified_by', $add, true)) {
                $t->string('id_verified_by', 64)->nullable();
            }
            if (in_array('review_notified_at', $add, true)) {
                $t->timestamp('review_notified_at')->nullable();
            }
        });

        $now = now();

        if (in_array('id_verified_at', $add, true)) {
            $real = array_map('strval', (array) config('tutors.real_user_ids', []));
            DB::table('register')
                ->where('join_as', 'teacher')
                ->where('status', 't')
                ->when(Schema::hasColumn('register', 'is_sample'), fn ($q) => $q->where(fn ($w) => $w->where('is_sample', 0)->orWhereNull('is_sample')))
                ->where(fn ($w) => $w->whereIn('user_id', $real ?: ['__none__'])
                    ->orWhere(fn ($p) => $p->whereNotNull('phone')->where('phone', '!=', '')))
                ->update(['id_verified_at' => $now, 'id_verified_by' => 'backfill-2026-10-03']);
        }

        if (in_array('review_notified_at', $add, true)) {
            DB::table('register')->where('join_as', 'teacher')->update(['review_notified_at' => $now]);
        }
    }

    public function down(): void
    {
        if (! Schema::hasTable('register')) {
            return;
        }
        $drop = array_values(array_filter(
            ['id_verified_at', 'id_verified_by', 'review_notified_at'],
            fn ($c) => Schema::hasColumn('register', $c),
        ));
        if ($drop !== []) {
            Schema::table('register', fn (Blueprint $t) => $t->dropColumn($drop));
        }
    }
};
