<?php

/*
 * Sector of area pages named after a housing society or locality, so they
 * get their zone (config/zones.php) on the area page: the zone block, the
 * neighbouring areas and anonymised requests. Researched 30 Sep 2026; each
 * was checked against a developer, RERA or property-portal listing (the
 * source follows each entry). Projects spanning two sectors list both; the
 * zone comes from the first. Pages in Sohna town's own sector numbering are
 * left out, since "Sector 33" there is not Gurugram's Sector 33.
 * Keyed by the area page slug, per city page slug.
 */
return [
    'gurugram' => [
        'adani-aangan' => 'Sector 88A', // https://www.adanirealty.com/residential-projects/gurugram/aangan
        'adani-m2k-oyster-grande-2' => 'Sector 102', // https://www.squareyards.com/gurgaon-residential-property/adani-m2k-oyster-grande/220/project
        'adani-oyster-grande' => 'Sector 102', // https://www.squareyards.com/gurgaon-residential-property/adani-m2k-oyster-grande/220/project
        'adani-oyster-grande-phase-2' => 'Sector 102', // https://www.squareyards.com/gurgaon-residential-property/adani-m2k-oyster-grande/220/project
        'ambience-caitriona' => 'Sector 24', // https://www.squareyards.com/gurgaon-residential-property/ambience-caitriona/340/project
        'ambience-lagoon' => 'Sector 24', // https://www.squareyards.com/gurgaon-residential-property/ambience-island-lagoon/343/project
        'anant-raj-estate' => 'Sector 63A', // https://www.squareyards.com/gurgaon-residential-property/anant-raj-estate-plots/20927/project
        'anant-raj-maceo' => 'Sector 91', // https://www.squareyards.com/gurgaon-residential-property/anant-raj-maceo/153/project
        'ansal-esencia' => 'Sector 67', // https://www.99acres.com/ansal-api-esencia-resale-in-sector-67-gurgaon-15104-npffid
        'ansal-florence-residency' => 'Sector 57', // https://www.squareyards.com/gurgaon-residential-property/ansal-florence-residency/20954/project
        'ansal-highland-park' => 'Sector 103', // https://www.ansals.com/home/project_detail/ansals-highland-park
        'ansal-versalia' => 'Sector 67A', // https://www.squareyards.com/gurgaon-residential-property/ansal-api-versalia/394/project
        'ats-grandstand' => 'Sector 99A', // https://www.99acres.com/ats-grandstand-sector-99a-gurgaon-npxid-r308927
        'ats-kocoon' => 'Sector 109', // https://www.99acres.com/ats-kocoon-sector-109-gurgaon-npxid-r24656
        'ats-tourmaline' => 'Sector 109', // https://www.ats.ind.in/projects-in-gurugram/ats-tourmaline-sector-109-dwarka-expressway/
        'baani-square-residences' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/baani-square/121282/project
        'bestech-park-view-city-1' => 'Sector 48', // https://www.squareyards.com/gurgaon-residential-property/bestech-park-view-city-1/297/project
        'bestech-park-view-city-2' => 'Sector 49', // https://bestechgroup.com/park-view-city-2.php
        'bestech-park-view-sanskruti' => 'Sector 92', // https://www.99acres.com/bestech-park-view-sanskruti-sector-92-gurgaon-npxid-r4600
        'bestech-park-view-spa' => 'Sector 47', // https://jaguarlandbase.com/bestech-park-view-spa-sector-47-gurgaon
        'bestech-park-view-spa-next' => 'Sector 67', // https://www.squareyards.com/gurgaon-residential-property/bestech-park-view-spa-next/53/project
        'beverly-park-1' => 'Sector 25', // https://beverlypark1.in/
        'beverly-park-2' => 'Sector 25', // https://www.squareyards.com/gurgaon-residential-property/dlf-beverly-park-ii/20989/project
        'birla-navya' => 'Sector 63A', // https://www.birlaestateshomes.com/project/birla-navya-avik-phase-1-in-sector-63-a-gurgaon/index.html
        'birla-navya--anaikadrisha' => 'Sector 63A', // https://www.birlaestateshomes.com/project/birla-navya-avik-phase-1-in-sector-63-a-gurgaon/index.html
        'bptp-amstoria' => 'Sector 102', // https://www.bptp.com/projects/amstoria
        'bptp-astaire-gardens' => 'Sector 70A', // https://www.bptp.com/projects/astaire-gardens
        'bptp-monet-floors' => 'Sector 70A', // https://www.99acres.com/bptp-monet-avant-floors-sector-70a-gurgaon-npxid-r72887
        'bptp-park-life' => 'Sector 57', // https://www.squareyards.com/gurgaon-residential-property/bptp-freedom-park-life/65/project
        'bptp-park-prime' => 'Sector 66', // https://www.squareyards.com/gurgaon-residential-property/bptp-park-prime/88/project
        'bptp-terra' => 'Sector 37D', // https://www.squareyards.com/gurgaon-residential-property/bptp-terra/270/project
        'central-park-2-the-roombelgravia' => 'Sector 48', // https://www.squareyards.com/gurgaon-residential-property/central-park-ii-belgravia-resort-residences/313/project
        'central-park-resorts--the-room' => 'Sector 48', // https://www.squareyards.com/gurgaon-residential-property/central-park-resorts/106940/project
        'conscient-elevate-tower-5' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/conscient-hines-elevate/10610/project
        'conscient-heritage-max' => 'Sector 102', // https://www.squareyards.com/gurgaon-residential-property/conscient-heritage-max/229/project
        'conscient-hines-elevate' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/conscient-hines-elevate/10610/project
        'conscient-one-residences' => 'Sector 109', // https://www.99acres.com/conscient-one-resale-in-sector-109-gurgaon-36784-npffid
        'dlf-alameda' => 'Sector 73', // https://www.99acres.com/dlf-alameda-sector-73-gurgaon-npxid-r1229
        'dlf-aralias' => 'Sector 42', // https://www.vrkhomeestates.com/dlf-the-aralias/
        'dlf-belvedere-park' => 'Sector 24', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-belvedere-park/344/project
        'dlf-belvedere-tower' => 'Sector 24', // https://www.squareyards.com/gurgaon-residential-property/dlf-belvedere-towers/347/project
        'dlf-camellias' => 'Sector 42', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-camellias/358/project
        'dlf-central-park-1' => 'Sector 42', // https://www.hcorealestates.com/project/central-park-1-gurgaon
        'dlf-crest' => 'Sector 54', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-crest/342/project
        'dlf-garden-city' => 'Sectors 91-92', // https://www.100acress.com/dlf-garden-city-floors/
        'dlf-icon' => 'Sector 43', // https://www.homebazaar.com/dlf-the-icon-sector-43-gurgaon-572
        'dlf-magnolias' => 'Sector 42', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-magnolias/333/project
        'dlf-new-town-heights-90' => 'Sector 90', // https://www.realtyventuresindia.com/property/dlf-new-town-heights-86-90-91/
        'dlf-new-town-heights-91' => 'Sector 91', // https://www.realtyventuresindia.com/property/dlf-new-town-heights-86-90-91/
        'dlf-park-place' => 'Sector 54', // https://www.homebazaar.com/dlf-park-place-sector-54-gurgaon-1118
        'dlf-princeton-estate' => 'Sector 53', // https://www.nobroker.in/dlf-princeton-estate-sector-53_gurgaon-prjt-5ba00ebd714b5687a7dc8c43
        'dlf-princeton-estate-blocks-ae' => 'Sector 53', // https://www.nobroker.in/dlf-princeton-estate-sector-53_gurgaon-prjt-5ba00ebd714b5687a7dc8c43
        'dlf-privana' => 'Sectors 76-77', // https://www.dlf.in/homes/luxury/privanasouth/
        'dlf-regal-gardens' => 'Sector 90', // https://www.squareyards.com/gurgaon-residential-property/dlf-regal-gardens/166/project
        'dlf-regency-park-2' => 'Sector 27', // https://www.squareyards.com/gurgaon-residential-property/dlf-regency-park-ii/354/project
        'dlf-ridgewood-estate' => 'Sector 27', // https://www.nobroker.in/dlf-ridgewood-estate-sector-27_gurgaon-prjt-5ba00ebd714b5687a7dc8ca0
        'dlf-silver-oaks' => 'Sector 26', // https://www.squareyards.com/gurgaon-residential-property/dlf-silver-oaks/361/project
        'dlf-sky-court' => 'Sector 86', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-skycourt/114/project
        'dlf-summit' => 'Sector 54', // https://www.homebazaar.com/dlf-the-summit-sector-54-gurgaon-558
        'dlf-the-belaire' => 'Sector 54', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-belaire/338/project
        'dlf-the-skycourt-inh' => 'Sector 86', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-skycourt/114/project
        'dlf-wellington-estate' => 'Sector 53', // https://www.nobroker.in/dlf-wellington-estate-sector-53_gurgaon-prjt-5ba00ebd714b5687a7dc8c94
        'emaar-digital-greens-residences' => 'Sector 61', // https://www.99acres.com/emaar-digital-greens-sector-61-gurgaon-npxid-c37
        'emaar-digital-greens-residences-2' => 'Sector 61', // https://www.99acres.com/emaar-digital-greens-sector-61-gurgaon-npxid-c37
        'emaar-emerald-estate-floors' => 'Sector 65', // https://houssed.com/gurgaon/emaar-group/emaar-emerald-estate-4660
        'emaar-emerald-floors-premier' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/emaar-emerald-floors-premier/62/project
        'emaar-emerald-hills' => 'Sector 65', // https://in.emaar.com/en/our-communities/emerald-hills/
        'emaar-emerald-plaza-residences' => 'Sector 65', // https://in.emaar.com/en/our-communities/emerald-hills/
        'emaar-imperial-gardens' => 'Sector 102', // https://in.emaar.com/en/properties/imperial-gardens/
        'emaar-marbella' => 'Sector 66', // https://www.squareyards.com/gurgaon-residential-property/emaar-marbella/67/project
        'emaar-mgf-the-enclave' => 'Sector 66', // https://www.squareyards.com/gurgaon-residential-property/emaar-the-enclave/77/project
        'emaar-palm-drive' => 'Sector 66', // https://www.99acres.com/emaar-mgf-the-palm-drive-sector-66-gurgaon-npxid-r19
        'emaar-palm-drive--sky-terraces' => 'Sector 66', // https://www.99acres.com/emaar-mgf-the-palm-drive-sector-66-gurgaon-npxid-r19
        'emaar-palm-gardens' => 'Sector 83', // https://www.squareyards.com/gurgaon-residential-property/emaar-palm-gardens/73/project
        'emaar-palm-hills' => 'Sector 77', // https://www.squareyards.com/gurgaon-residential-property/emaar-palm-hills/136/project
        'emaar-palm-terrace-select' => 'Sector 66', // https://www.99acres.com/emaar-mgf-palm-terraces-select-sector-66-gurgaon-npxid-r904
        'emerald-estate-emaar' => 'Sector 65', // https://houssed.com/gurgaon/emaar-group/emaar-emerald-estate-4660
        'emerald-floors-emaar' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/emaar-emerald-floors-premier/62/project
        'eros-rosewood-city-floors' => 'Sectors 49-50', // https://www.squareyards.com/gurgaon-residential-property/eros-rosewood-city/21257/project
        'eros-wembley-estate' => 'Sector 50', // https://www.99acres.com/eros-wembley-estate-sector-50-gurgaon-npxid-r8260
        'essel-towers' => 'Sector 28', // https://www.squareyards.com/gurgaon-residential-property/suncity-essel-tower/377/project
        'experion-heartsong' => 'Sector 108', // https://www.squareyards.com/gurgaon-residential-property/experion-the-heart-song/222/project
        'experion-the-westerlies-villas' => 'Sector 108', // https://www.squareyards.com/gurgaon-residential-property/experion-the-westerlies/352/project
        'experion-windchants' => 'Sector 112', // https://www.squareyards.com/gurgaon-residential-property/experion-windchants/256/project
        'experion-windchants-villas' => 'Sector 112', // https://www.squareyards.com/gurgaon-residential-property/experion-windchants/256/project
        'godrej-air' => 'Sector 85', // https://www.godrejproperties.com/gurugram/residential/godrej-air
        'godrej-frontier' => 'Sector 80', // https://www.squareyards.com/gurgaon-residential-property/godrej-frontier/125/project
        'godrej-oasis' => 'Sector 88A', // https://www.godrejproperties.com/gurugram/residential/godrej-oasis
        'godrej-summit' => 'Sector 104', // https://www.godrejproperties.com/gurugram/residential/godrej-summit
        'greenwood-city' => 'Sectors 45-46', // https://www.99acres.com/greenwood-city-gurgaon-overview-piffid
        'heritage-one' => 'Sector 62', // https://www.squareyards.com/gurgaon-residential-property/conscient-heritage-one/94/project
        'heritage-one-residences' => 'Sector 62', // https://www.squareyards.com/gurgaon-residential-property/conscient-heritage-one/94/project
        'hines-elevate' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/conscient-hines-elevate/10610/project
        'ild-grand' => 'Sector 37C', // https://www.squareyards.com/gurgaon-residential-property/ild-grand/273/project
        'indiabulls-centrum-park' => 'Sector 103', // https://www.squareyards.com/gurgaon-residential-property/indiabulls-centrum-park/249/project
        'indiabulls-enigma' => 'Sector 110', // https://www.squareyards.com/gurgaon-residential-property/indiabulls-enigma/254/project
        'indiabulls-one-09-residences' => 'Sector 109', // https://www.squareyards.com/gurgaon-residential-property/indiabulls-one-09/8694/project
        'ireo-corridors' => 'Sector 67A', // https://www.squareyards.com/gurgaon-residential-property/ireo-the-corridors/309/project
        'ireo-grand-arch' => 'Sector 58', // https://www.99acres.com/ireo-the-grand-arch-resale-in-sector-58-gurgaon-12210-npffid
        'ireo-skyon-towers-bd' => 'Sector 60', // https://www.squareyards.com/gurgaon-residential-property/ireo-skyon/64/project
        'ireo-uptown' => 'Sector 66', // https://www.squareyards.com/gurgaon-residential-property/ireo-uptown/52/project
        'ireo-victory-valley' => 'Sector 67', // https://www.squareyards.com/gurgaon-residential-property/ireo-victory-valley/55/project
        'joyville-gurugram-mahindra' => 'Sector 102', // https://www.joyvillehomes.com/joyville-gurugram/
        'm3m-corner-walk-residences' => 'Sector 74', // https://www.99acres.com/m3m-corner-walk-sector-74-gurgaon-npxid-c9631
        'm3m-escala' => 'Sector 70A', // https://www.99acres.com/m3m-escala-sector-70a-gurgaon-npxid-r17682
        'm3m-fairway-west-golfestate' => 'Sector 65', // https://m3mindia.com/residential/m3m-fairway-west
        'm3m-golfestate' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/m3m-golf-estate/68/project
        'm3m-latitude' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/m3m-latitude/986/project
        'm3m-merlin' => 'Sector 67', // https://www.squareyards.com/gurgaon-residential-property/m3m-merlin/61/project
        'm3m-myden' => 'Sector 67', // https://www.squareyards.com/gurgaon-residential-property/m3m-my-den/143097/project
        'm3m-natur' => 'Sector 68', // https://www.squareyards.com/gurgaon-residential-property/m3m-natura/10511/project
        'm3m-polo-suites' => 'Sector 65', // https://www.99acres.com/m3m-polo-suites-sector-65-gurgaon-npxid-r1242
        'm3m-sky-city-residences' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/m3m-sky-city/10917/project
        'm3m-st-andrews-golfestate' => 'Sector 65', // https://www.squareyards.com/gurgaon-residential-property/m3m-golf-estate/68/project
        'mahindra-aura' => 'Sector 110A', // https://www.squareyards.com/gurgaon-residential-property/mahindra-aura/272/project
        'mahindra-luminare' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/mahindra-luminare/987/project
        'mahindra-luminare-c' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/mahindra-luminare/987/project
        'mapsko-casa-bella' => 'Sector 82', // https://www.squareyards.com/gurgaon-residential-property/mapsko-casa-bella-villas/139/project
        'mapsko-casa-bella-extension' => 'Sector 82', // https://www.squareyards.com/gurgaon-residential-property/mapsko-casa-bella-villas/139/project
        'mapsko-royale-ville' => 'Sector 82', // https://www.squareyards.com/gurgaon-residential-property/mapsko-royale-ville/128/project
        'ninex-city' => 'Sector 76', // https://www.99acres.com/ninex-city-sector-76-gurgaon-npxid-r11294
        'ninex-rmg-residency' => 'Sector 37C', // https://www.squareyards.com/gurgaon-residential-property/ninex-rmg-residency/8465/project
        'orchid-island' => 'Sector 51', // https://www.squareyards.com/gurgaon-residential-property/orchid-island/87/project
        'orchid-petals' => 'Sector 49', // https://www.99acres.com/orchid-petals-sector-49-gurgaon-npxid-r12066
        'palm-springs-plaza-residences' => 'Sector 54', // https://emaarindiaprojects.com/emaar-palm-spring-plaza/
        'paras-dews' => 'Sector 106', // https://www.squareyards.com/gurgaon-residential-property/paras-dews/247/project
        'paras-irene' => 'Sector 70A', // https://www.99acres.com/paras-irene-sector-70a-gurgaon-npxid-r2388
        'paras-quartier' => 'Sector 2', // https://houssed.com/gurgaon/paras-buildtech/paras-quartier-4305
        'park-view-grand-spa' => 'Sector 81', // https://www.99acres.com/bestech-park-view-grand-spa-sector-81-gurgaon-npxid-r2086
        'park-view-residency' => 'Sector 3', // https://www.squareyards.com/gurgaon-residential-property/bestech-park-view-residency/345/project
        'pioneer-araya-sky-villas' => 'Sector 62', // https://www.99acres.com/pioneer-araya-sector-62-gurgaon-npxid-r1325
        'pioneer-park' => 'Sector 61', // https://www.squareyards.com/gurgaon-residential-property/pioneer-park-phase-1/74/project
        'pioneer-presidia' => 'Sector 62', // https://www.nobroker.in/pioneer-presidia-sector-62_gurgaon-prjt-8a9fd182886c32c401886c8c87f039ea
        'pioneer-urban-araya' => 'Sector 62', // https://www.99acres.com/pioneer-araya-sector-62-gurgaon-npxid-r1325
        'raheja-atlantis' => 'Sector 31', // https://www.squareyards.com/gurgaon-residential-property/raheja-atlantis/349/project
        'raheja-revanta' => 'Sector 78', // https://www.99acres.com/raheja-revanta-sector-78-gurgaon-npxid-r1263
        'raheja-shilas' => 'Sector 109', // https://www.99acres.com/raheja-shilas-sector-109-gurgaon-npxid-r635
        'raheja-vedas' => 'Sector 108', // https://gharpe.com/gurgaon/raheja-vedas
        'ramprastha-city' => 'Sectors 37C-37D', // https://www.haryanarera.gov.in/view_project/project_preview_open/841
        'ramprastha-primera' => 'Sector 37D', // https://www.99acres.com/ramprastha-primera-sector-37d-gurgaon-npxid-r4640
        'ramprastha-rise' => 'Sector 37D', // https://www.squareyards.com/gurgaon-residential-property/ramprastha-city-rise/266/project
        'ramprastha-the-edge-towers' => 'Sector 37D', // https://www.squareyards.com/gurgaon-residential-property/ramprastha-city-the-edge-towers/280/project
        'rosewood-city' => 'Sectors 49-50', // https://www.squareyards.com/gurgaon-residential-property/eros-rosewood-city/21257/project
        'sahara-grace' => 'Sector 28', // https://www.squareyards.com/gurgaon-residential-property/sahara-grace-gurgaon/362/project
        'sare-crescent-parc' => 'Sector 92', // https://www.squareyards.com/gurgaon-residential-property/sare-crescent-parc-royal-greens-phase-i/179/project
        'sare-royal-greens' => 'Sector 92', // https://www.99acres.com/sare-crescent-parc-royal-greens-phase-1-sector-92-gurgaon-npxid-r26258
        'signature-global-grand-iva' => 'Sector 103', // https://www.signatureglobal.in/residential/grand-iva-sector-103-gurugram
        'signature-global-orchard-avenue' => 'Sector 93', // https://www.99acres.com/signature-global-orchard-avenue-sector-93-gurgaon-npxid-r265101
        'signature-global-solera' => 'Sector 107', // https://www.signatureglobal.in/residential/solera
        'signature-global-synera' => 'Sector 81', // https://www.99acres.com/signature-global-synera-sector-81-gurgaon-npxid-r99240
        'signature-global-the-millennia' => 'Sector 37D', // https://www.squareyards.com/gurgaon-residential-property/signature-global-the-millennia/143692/project
        'spaze-arrow-residences' => 'Sector 78', // https://www.99acres.com/spaze-arrow-sector-78-gurgaon-npxid-c206
        'spaze-privy' => 'Sector 72', // https://www.squareyards.com/gurgaon-residential-property/spaze-privy/290/project
        'spaze-privy-at4' => 'Sector 84', // https://www.squareyards.com/gurgaon-residential-property/spaze-privy-at4/106/project
        'spaze-privy-residences' => 'Sector 72', // https://www.squareyards.com/gurgaon-residential-property/spaze-privy/290/project
        'ss-coralwood' => 'Sector 84', // https://www.squareyards.com/gurgaon-residential-property/ss-the-coralwood/111/project
        'ss-linden' => 'Sectors 84-85', // https://propertyingurugram.in/residential/ss-linden-floors-sector-84-85-gurgaon/
        'ss-omnia-residences' => 'Sector 86', // https://gurgaon-ssgroup.com/ss-omnia/
        'ss-the-hibiscus' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/ss-hibiscus/110/project
        'ss-the-leaf' => 'Sector 85', // https://www.squareyards.com/gurgaon-residential-property/ss-the-leaf/115/project
        'sun-city' => 'Sector 54', // https://www.squareyards.com/gurgaon-residential-property/suncity-township-gurgaon/21181/project
        'suncity-apartments' => 'Sector 54', // https://www.squareyards.com/gurgaon-residential-property/suncity-township-gurgaon/21181/project
        'suncity-heights' => 'Sector 54', // https://www.99acres.com/suncity-heights-sector-54-gurgaon-npxid-r11960
        'supertech-araville' => 'Sector 79', // https://www.squareyards.com/gurgaon-residential-property/supertech-araville/144/project
        'supertech-hues' => 'Sector 68', // https://www.squareyards.com/gurgaon-residential-property/supertech-hues/499/project
        'tata-la-vida' => 'Sector 113', // https://www.99acres.com/la-vida-by-tata-housing-sector-113-gurgaon-npxid-r265503
        'tata-primanti' => 'Sector 72', // https://www.tatahousing.com/residential-property-in-gurgaon/tata-primanti
        'tata-raisina-residency' => 'Sector 59', // https://www.squareyards.com/gurgaon-residential-property/tata-raheja-raisina-residency/80/project
        'the-aralias-tower-af' => 'Sector 42', // https://www.vrkhomeestates.com/dlf-the-aralias/
        'the-camellias-towers-ah' => 'Sector 42', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-camellias/358/project
        'the-crest-tower-16' => 'Sector 54', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-crest/342/project
        'the-magnolias-towers-19' => 'Sector 42', // https://www.squareyards.com/gurgaon-residential-property/dlf-the-magnolias/333/project
        'the-palm-springs' => 'Sector 54', // https://www.99acres.com/emaar-the-palm-springs-sector-54-gurgaon-npxid-r12084
        'tulip-ace' => 'Sector 89', // https://www.squareyards.com/gurgaon-residential-property/tulip-ace/169/project
        'tulip-ivory' => 'Sector 70', // https://www.nobroker.in/tulip-ivory-sector-70_gurgaon-prjt-5e972b19a5a1662dac0a6b04
        'tulip-lemon' => 'Sector 69', // https://www.99acres.com/tulip-lemon-reviews-ratings-sector-69-gurgaon-npxid-r119221
        'tulip-petals' => 'Sector 89', // https://www.99acres.com/tulip-petals-sector-89-gurgaon-npxid-r26374
        'tulip-purple' => 'Sector 69', // https://www.360realtors.com/tulip-purple-sector-69-gurgaon-uid-238
        'tulip-violet' => 'Sector 69', // https://www.squareyards.com/gurgaon-residential-property/tulip-violet/395/project
        'tulip-white' => 'Sector 69', // https://www.squareyards.com/gurgaon-residential-property/tulip-white/190/project
        'umang-winter-hills' => 'Sector 77', // https://haryanarera.gov.in/view_project/searchprojectDetail/2851
        'unitech-escape' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/unitech-escape/83/project
        'unitech-fresco' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/unitech-fresco/51/project
        'unitech-harmony' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/unitech-harmony/85/project
        'unitech-south-park' => 'Sector 70', // https://www.unitechgroup.com/residential-properties/gurgaon/unitech-south-park.asp
        'unitech-sunbreeze' => 'Sector 69', // https://www.squareyards.com/gurgaon-residential-property/unitech-sunbreeze/21133/project
        'unitech-the-close-north' => 'Sector 50', // https://www.squareyards.com/gurgaon-residential-property/unitech-the-close-north/54/project
        'unitech-the-close-south' => 'Sector 50', // https://www.squareyards.com/sale/resale-properties-in-unitech-the-close-south-gurgaon
        'unitech-the-palms' => 'Sector 41', // https://www.99acres.com/unitech-the-palms-sector-41-gurgaon-npxid-r29768
        'unitech-uniworld-gardens-1' => 'Sector 47', // https://www.squareyards.com/gurgaon-residential-property/unitech-uniworld-gardens/296/project
        'unitech-uniworld-gardens-2' => 'Sector 47', // https://www.unitechgroup.com/residential-properties/gurgaon/uniworld-gardens2.asp
        'unitech-uniworld-resorts' => 'Sector 33', // https://www.squareyards.com/gurgaon-residential-property/unitech-uniworld-resorts-the-residences/289/project
        'unitech-world-spa' => 'Sectors 30 & 41', // https://www.nobroker.in/unitech-the-world-spa-sector-30_gurgaon-prjt-5ba00ebd714b5687a7dc8e51
        'uppal-southend' => 'Sector 49', // https://www.squareyards.com/gurgaon-residential-property/uppal-southend/21151/project
        // Pages covering a sector range: the zone of the first sector.
        'sectors-2628' => 'Sector 26',
        'sectors-4546' => 'Sector 45',
        'sectors-4752-' => 'Sector 47',
        'sectors-9192' => 'Sector 91',
    ],
];
