<?php

/*
|--------------------------------------------------------------------------
| Subject pages: /maths-home-tutor, /maths-home-tutor/class-10, …
|--------------------------------------------------------------------------
|
| One entry per URL. A page is served only if it is listed here AND its
| guide exists at resources/views/subjects/content/{view}.blade.php, so a
| half-written page can never go live by accident.
|
|   subject  what the tutor search filters on (SubjectNormalizer names)
|   class    class filter for tutor cards, e.g. "Class 10" (optional)
|   city     city filter and local wording (optional; null = all India)
|   parent   the page above this one in the breadcrumb (optional)
|   authors  keys from config/nx_authors.php; the first is the byline
|   title/description/h1/lede  the page's own words
|
| Content and FAQs live in resources/views/subjects/{content,faqs}/{view}.
*/

return [
    'maths-home-tutor' => [
        'view' => 'maths-home-tutor',
        'subject' => 'Mathematics',
        'label' => 'Maths home tutors',
        'title' => 'Maths Home Tutor – Classes 5–12, CBSE, ICSE, IB & IGCSE | NXTutors',
        'description' => 'Verified maths home tutors and online maths tutors for Classes 5–12: CBSE, ICSE, IB, IGCSE and JEE. See matched tutors, fees and a free demo class.',
        'h1' => 'Maths Home Tutors for Classes 5–12',
        'lede' => 'Verified maths tutors at home or online, matched to your child’s class, board and pace — CBSE, ICSE, IB, IGCSE and JEE.',
        'authors' => ['ajay', 'abhinandan'],
    ],
    'maths-home-tutor/class-10' => [
        'view' => 'maths-home-tutor--class-10',
        'subject' => 'Mathematics',
        'class' => 'Class 10',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 10',
        'title' => 'Maths Home Tutor for Class 10 – CBSE & ICSE 2026-27 | NXTutors',
        'description' => 'Class 10 maths home tutors for CBSE and ICSE boards 2026-27: chapter weightage, a month-by-month plan, fees and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 10 (CBSE & ICSE)',
        'lede' => 'Board-year maths with a tutor who knows the 2026-27 paper: chapter weightage, step marking and a plan that ends with full papers.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor-gurgaon' => [
        'view' => 'maths-home-tutor-gurgaon',
        'subject' => 'Mathematics',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'maths-home-tutor',
        'label' => 'Gurugram',
        'title' => 'Maths Home Tutor in Gurgaon – CBSE, ICSE, IB & IGCSE | NXTutors',
        'description' => 'Maths home tutors in Gurgaon (Gurugram) for CBSE, ICSE, IB and IGCSE, Classes 5–12 and JEE. Verified tutors near your sector, with a free demo class.',
        'h1' => 'Maths Home Tutors in Gurgaon (Gurugram)',
        'lede' => 'Verified maths tutors across Gurugram’s sectors and societies — CBSE, ICSE, IB and IGCSE — at home or online, with a free demo class.',
        'authors' => ['ajay', 'abhinandan'],
    ],
    'science-home-tutor' => [
        'view' => 'science-home-tutor',
        'subject' => 'Science',
        'label' => 'Science home tutors',
        'title' => 'Science Home Tutor – Classes 6–10, CBSE & ICSE | NXTutors',
        'description' => 'Verified science home tutors and online science tutors for Classes 6–10, CBSE and ICSE. Concepts, diagrams and numericals, with a free demo class.',
        'h1' => 'Science Home Tutors for Classes 6–10',
        'lede' => 'Physics, chemistry and biology taught the way the board marks them — concepts first, then diagrams, numericals and answers that score.',
        'authors' => ['aaditya'],
    ],
    'science-home-tutor/class-10' => [
        'view' => 'science-home-tutor--class-10',
        'subject' => 'Science',
        'class' => 'Class 10',
        'parent' => 'science-home-tutor',
        'label' => 'Class 10',
        'title' => 'Science Home Tutor for Class 10 – CBSE & ICSE 2026-27 | NXTutors',
        'description' => 'Class 10 science home tutors for CBSE and ICSE 2026-27: chapter weightage, diagrams, numericals and a board plan, at home or online. Free demo class.',
        'h1' => 'Science Home Tutor for Class 10 (CBSE & ICSE)',
        'lede' => 'Chemistry, biology and physics for the board year, with a tutor who drills the diagrams, equations and numericals examiners look for.',
        'authors' => ['aaditya'],
    ],
    'maths-home-tutor/class-5' => [
        'view' => 'maths-home-tutor--class-5',
        'subject' => 'Mathematics',
        'class' => 'Class 5',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 5',
        'title' => 'Maths Home Tutor for Class 5 – CBSE, ICSE & More | NXTutors',
        'description' => 'Class 5 maths home tutors for CBSE and ICSE: the syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 5',
        'lede' => 'Class 5 maths taught at your child\'s pace: the chapters that matter this year, and the habits that make the next one easier.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor/class-6' => [
        'view' => 'maths-home-tutor--class-6',
        'subject' => 'Mathematics',
        'class' => 'Class 6',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 6',
        'title' => 'Maths Home Tutor for Class 6 – CBSE, ICSE & More | NXTutors',
        'description' => 'Class 6 maths home tutors for CBSE and ICSE: the syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 6',
        'lede' => 'Class 6 maths taught at your child\'s pace: the chapters that matter this year, and the habits that make the next one easier.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor/class-7' => [
        'view' => 'maths-home-tutor--class-7',
        'subject' => 'Mathematics',
        'class' => 'Class 7',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 7',
        'title' => 'Maths Home Tutor for Class 7 – CBSE, ICSE & More | NXTutors',
        'description' => 'Class 7 maths home tutors for CBSE and ICSE: the syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 7',
        'lede' => 'Class 7 maths taught at your child\'s pace: the chapters that matter this year, and the habits that make the next one easier.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor/class-8' => [
        'view' => 'maths-home-tutor--class-8',
        'subject' => 'Mathematics',
        'class' => 'Class 8',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 8',
        'title' => 'Maths Home Tutor for Class 8 – CBSE, ICSE & More | NXTutors',
        'description' => 'Class 8 maths home tutors for CBSE and ICSE: the syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 8',
        'lede' => 'Class 8 maths taught at your child\'s pace: the chapters that matter this year, and the habits that make the next one easier.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor/class-9' => [
        'view' => 'maths-home-tutor--class-9',
        'subject' => 'Mathematics',
        'class' => 'Class 9',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 9',
        'title' => 'Maths Home Tutor for Class 9 – CBSE, ICSE & More | NXTutors',
        'description' => 'Class 9 maths home tutors for CBSE and ICSE: the syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 9',
        'lede' => 'Class 9 maths taught at your child\'s pace: the chapters that matter this year, and the habits that make the next one easier.',
        'authors' => ['abhinandan', 'ajay'],
    ],
    'maths-home-tutor/class-11' => [
        'view' => 'maths-home-tutor--class-11',
        'subject' => 'Mathematics',
        'class' => 'Class 11',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 11',
        'title' => 'Maths Home Tutor for Class 11 – CBSE, ICSE, ISC & More | NXTutors',
        'description' => 'Class 11 maths home tutors for CBSE and ICSE and ISC, with JEE foundations: the 2026-27 syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 11',
        'lede' => 'Class 11 is where JEE and board maths both begin in earnest: a tutor who builds algebra, trigonometry and calculus foundations properly.',
        'authors' => ['ajay', 'abhinandan'],
    ],
    'maths-home-tutor/class-12' => [
        'view' => 'maths-home-tutor--class-12',
        'subject' => 'Mathematics',
        'class' => 'Class 12',
        'parent' => 'maths-home-tutor',
        'label' => 'Class 12',
        'title' => 'Maths Home Tutor for Class 12 – CBSE, ICSE, ISC & More | NXTutors',
        'description' => 'Class 12 maths home tutors for CBSE and ICSE and ISC, with JEE foundations: the 2026-27 syllabus explained, a weekly plan and a free demo class, at home or online.',
        'h1' => 'Maths Home Tutor for Class 12',
        'lede' => 'Board-year calculus, vectors and probability with a tutor who knows the 2026-27 paper and, where needed, JEE.',
        'authors' => ['ajay', 'abhinandan'],
    ],
    'science-home-tutor/class-6' => [
        'view' => 'science-home-tutor--class-6',
        'subject' => 'Science',
        'class' => 'Class 6',
        'parent' => 'science-home-tutor',
        'label' => 'Class 6',
        'title' => 'Science Home Tutor for Class 6 – CBSE & ICSE | NXTutors',
        'description' => 'Class 6 science home tutors for CBSE and ICSE: this year\'s chapters, experiments, diagrams and a weekly plan, at home or online. Free demo class.',
        'h1' => 'Science Home Tutor for Class 6',
        'lede' => 'Class 6 science made clear and hands-on: the concepts, diagrams and questions this year asks for, with a tutor who teaches why, not just what.',
        'authors' => ['aaditya'],
    ],
    'science-home-tutor/class-7' => [
        'view' => 'science-home-tutor--class-7',
        'subject' => 'Science',
        'class' => 'Class 7',
        'parent' => 'science-home-tutor',
        'label' => 'Class 7',
        'title' => 'Science Home Tutor for Class 7 – CBSE & ICSE | NXTutors',
        'description' => 'Class 7 science home tutors for CBSE and ICSE: this year\'s chapters, experiments, diagrams and a weekly plan, at home or online. Free demo class.',
        'h1' => 'Science Home Tutor for Class 7',
        'lede' => 'Class 7 science made clear and hands-on: the concepts, diagrams and questions this year asks for, with a tutor who teaches why, not just what.',
        'authors' => ['aaditya'],
    ],
    'science-home-tutor/class-8' => [
        'view' => 'science-home-tutor--class-8',
        'subject' => 'Science',
        'class' => 'Class 8',
        'parent' => 'science-home-tutor',
        'label' => 'Class 8',
        'title' => 'Science Home Tutor for Class 8 – CBSE & ICSE | NXTutors',
        'description' => 'Class 8 science home tutors for CBSE and ICSE: this year\'s chapters, experiments, diagrams and a weekly plan, at home or online. Free demo class.',
        'h1' => 'Science Home Tutor for Class 8',
        'lede' => 'Class 8 science made clear and hands-on: the concepts, diagrams and questions this year asks for, with a tutor who teaches why, not just what.',
        'authors' => ['aaditya'],
    ],
    'science-home-tutor/class-9' => [
        'view' => 'science-home-tutor--class-9',
        'subject' => 'Science',
        'class' => 'Class 9',
        'parent' => 'science-home-tutor',
        'label' => 'Class 9',
        'title' => 'Science Home Tutor for Class 9 – CBSE & ICSE | NXTutors',
        'description' => 'Class 9 science home tutors for CBSE and ICSE: this year\'s chapters, experiments, diagrams and a weekly plan, at home or online. Free demo class.',
        'h1' => 'Science Home Tutor for Class 9',
        'lede' => 'Class 9 science made clear and hands-on: the concepts, diagrams and questions this year asks for, with a tutor who teaches why, not just what.',
        'authors' => ['aaditya'],
    ],
    'physics-home-tutor' => [
        'view' => 'physics-home-tutor',
        'subject' => 'Physics',
        'label' => 'Physics home tutors',
        'title' => 'Physics Home Tutor – Class 11, 12, JEE & NEET | NXTutors',
        'description' => 'Verified physics home tutors and online physics tutors for Class 11 and 12, CBSE, ISC, IB and IGCSE, plus JEE and NEET physics. Free demo class.',
        'h1' => 'Physics Home Tutors for Class 11, 12, JEE & NEET',
        'lede' => 'Physics that makes sense: derivations, numericals and concepts taught step by step, for boards and entrance exams.',
        'authors' => ['nxtutors'],
    ],
    'physics-home-tutor/class-11' => [
        'view' => 'physics-home-tutor--class-11',
        'subject' => 'Physics',
        'parent' => 'physics-home-tutor',
        'label' => 'Class 11',
        'title' => 'Physics Home Tutor for Class 11 – CBSE, ISC & JEE | NXTutors',
        'description' => 'Class 11 physics home tutors: kinematics to waves, the 2026-27 syllabus, numericals and JEE/NEET foundations, at home or online. Free demo class.',
        'h1' => 'Physics Home Tutor for Class 11',
        'lede' => 'The hardest jump in school physics: vectors, mechanics and calculus-based problem solving, with a tutor who builds it properly.',
        'authors' => ['nxtutors'],
        'class' => 'Class 11',
    ],
    'physics-home-tutor/class-12' => [
        'view' => 'physics-home-tutor--class-12',
        'subject' => 'Physics',
        'parent' => 'physics-home-tutor',
        'label' => 'Class 12',
        'title' => 'Physics Home Tutor for Class 12 – CBSE 2026-27 & ISC | NXTutors',
        'description' => 'Class 12 physics home tutors for CBSE 2026-27 and ISC: unit weightage, derivations, numericals and board plus JEE/NEET preparation. Free demo class.',
        'h1' => 'Physics Home Tutor for Class 12',
        'lede' => 'Board-year physics: derivations, numericals and the chapters that carry the marks, with entrance-exam depth where you need it.',
        'authors' => ['nxtutors'],
        'class' => 'Class 12',
    ],
    'physics-home-tutor/neet' => [
        'view' => 'physics-home-tutor--neet',
        'subject' => 'Physics',
        'parent' => 'physics-home-tutor',
        'label' => 'NEET',
        'title' => 'Physics Home Tutor for NEET – NCERT-first Preparation | NXTutors',
        'description' => 'NEET physics home tutors: NCERT-first concepts, formula fluency and timed MCQ practice for the physics section. At home or online, free demo class.',
        'h1' => 'Physics Home Tutor for NEET',
        'lede' => 'The section most NEET aspirants fear, taught as concepts and patterns, not a formula dump.',
        'authors' => ['nxtutors'],
    ],
    'physics-home-tutor/jee' => [
        'view' => 'physics-home-tutor--jee',
        'subject' => 'Physics',
        'parent' => 'physics-home-tutor',
        'label' => 'JEE',
        'title' => 'Physics Home Tutor for JEE Main & Advanced | NXTutors',
        'description' => 'JEE physics home tutors for Main and Advanced: mechanics, electromagnetism and modern physics, problem-solving depth and test analysis. Free demo class.',
        'h1' => 'Physics Home Tutor for JEE (Main & Advanced)',
        'lede' => 'One-to-one JEE physics alongside coaching: doubt clearing, problem-solving depth and test analysis.',
        'authors' => ['nxtutors'],
    ],
    'chemistry-home-tutor' => [
        'view' => 'chemistry-home-tutor',
        'subject' => 'Chemistry',
        'label' => 'Chemistry home tutors',
        'title' => 'Chemistry Home Tutor – Class 11, 12 & NEET | NXTutors',
        'description' => 'Verified chemistry home tutors and online chemistry tutors for Class 11 and 12, CBSE, ISC, IB and IGCSE, plus NEET and JEE chemistry. Free demo class.',
        'h1' => 'Chemistry Home Tutors for Class 11, 12 & NEET',
        'lede' => 'Physical, organic and inorganic chemistry each need a different kind of teaching. Our tutors do all three.',
        'authors' => ['nxtutors'],
    ],
    'chemistry-home-tutor/class-11' => [
        'view' => 'chemistry-home-tutor--class-11',
        'subject' => 'Chemistry',
        'parent' => 'chemistry-home-tutor',
        'label' => 'Class 11',
        'title' => 'Chemistry Home Tutor for Class 11 – CBSE & ISC | NXTutors',
        'description' => 'Class 11 chemistry home tutors: mole concept, atomic structure, bonding, equilibrium and organic basics for CBSE and ISC, with NEET/JEE foundations.',
        'h1' => 'Chemistry Home Tutor for Class 11',
        'lede' => 'Class 11 chemistry lays every foundation Class 12 and NEET/JEE use, from the mole concept to organic basics.',
        'authors' => ['nxtutors'],
        'class' => 'Class 11',
    ],
    'chemistry-home-tutor/class-12' => [
        'view' => 'chemistry-home-tutor--class-12',
        'subject' => 'Chemistry',
        'parent' => 'chemistry-home-tutor',
        'label' => 'Class 12',
        'title' => 'Chemistry Home Tutor for Class 12 – CBSE 2026-27 & ISC | NXTutors',
        'description' => 'Class 12 chemistry home tutors for CBSE 2026-27 and ISC: unit weightage, organic mechanisms, named reactions and physical chemistry numericals.',
        'h1' => 'Chemistry Home Tutor for Class 12',
        'lede' => 'Board-year chemistry: organic reactions, physical chemistry numericals and inorganic from NCERT, planned by marks.',
        'authors' => ['nxtutors'],
        'class' => 'Class 12',
    ],
    'chemistry-home-tutor/neet' => [
        'view' => 'chemistry-home-tutor--neet',
        'subject' => 'Chemistry',
        'parent' => 'chemistry-home-tutor',
        'label' => 'NEET',
        'title' => 'Chemistry Home Tutor for NEET – NCERT Line by Line | NXTutors',
        'description' => 'NEET chemistry home tutors: NCERT-based inorganic, organic mechanisms and physical chemistry numericals, with timed MCQ practice. Free demo class.',
        'h1' => 'Chemistry Home Tutor for NEET',
        'lede' => 'The most scoring NEET section when it is taught from NCERT line by line, with a tutor who does exactly that.',
        'authors' => ['nxtutors'],
    ],
    'science-home-tutor-gurgaon' => [
        'view' => 'science-home-tutor-gurgaon',
        'subject' => 'Science',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'science-home-tutor',
        'label' => 'Gurugram',
        'title' => 'Science Home Tutor in Gurgaon – CBSE, ICSE, IB & IGCSE | NXTutors',
        'description' => 'Science home tutors in Gurgaon (Gurugram) for CBSE, ICSE, IB and IGCSE, Classes 6–10. Verified tutors near your sector, free demo class.',
        'h1' => 'Science Home Tutors in Gurgaon (Gurugram)',
        'lede' => 'Verified science tutors across Gurugram\'s sectors and societies, at home or online, matched to your child\'s board and class.',
        'authors' => ['aaditya'],
    ],
    'physics-home-tutor-gurgaon' => [
        'view' => 'physics-home-tutor-gurgaon',
        'subject' => 'Physics',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'physics-home-tutor',
        'label' => 'Gurugram',
        'title' => 'Physics Home Tutor in Gurgaon – CBSE, ICSE, IB & IGCSE | NXTutors',
        'description' => 'Physics home tutors in Gurgaon (Gurugram) for CBSE, ICSE, IB and IGCSE, Class 11–12, NEET and JEE. Verified tutors near your sector, free demo class.',
        'h1' => 'Physics Home Tutors in Gurgaon (Gurugram)',
        'lede' => 'Verified physics tutors across Gurugram\'s sectors and societies, at home or online, matched to your child\'s board and class.',
        'authors' => ['nxtutors'],
    ],
    'chemistry-home-tutor-gurgaon' => [
        'view' => 'chemistry-home-tutor-gurgaon',
        'subject' => 'Chemistry',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'chemistry-home-tutor',
        'label' => 'Gurugram',
        'title' => 'Chemistry Home Tutor in Gurgaon – CBSE, ICSE, IB & IGCSE | NXTutors',
        'description' => 'Chemistry home tutors in Gurgaon (Gurugram) for CBSE, ICSE, IB and IGCSE, Class 11–12, NEET and JEE. Verified tutors near your sector, free demo class.',
        'h1' => 'Chemistry Home Tutors in Gurgaon (Gurugram)',
        'lede' => 'Verified chemistry tutors across Gurugram\'s sectors and societies, at home or online, matched to your child\'s board and class.',
        'authors' => ['nxtutors'],
    ],
    'ib-maths-tutor-gurgaon' => [
        'view' => 'ib-maths-tutor-gurgaon',
        'subject' => 'Mathematics',
        'board' => 'IB',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'maths-home-tutor-gurgaon',
        'label' => 'IB Maths',
        'title' => 'IB Maths Tutor in Gurgaon – AA & AI, SL & HL | NXTutors',
        'description' => 'IB Maths tutors in Gurgaon for Analysis & Approaches and Applications & Interpretation, SL and HL, including the Internal Assessment. Free demo class.',
        'h1' => 'IB Maths Tutors in Gurgaon (AA & AI, SL & HL)',
        'lede' => 'Specialist IB maths tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['ajay'],
    ],
    'igcse-maths-tutor-gurgaon' => [
        'view' => 'igcse-maths-tutor-gurgaon',
        'subject' => 'Mathematics',
        'board' => 'IGCSE',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'maths-home-tutor-gurgaon',
        'label' => 'IGCSE Maths',
        'title' => 'IGCSE Maths Tutor in Gurgaon – Core & Extended | NXTutors',
        'description' => 'Cambridge IGCSE Maths tutors in Gurgaon for Core and Extended, calculator and non-calculator papers, past-paper practice. Free demo class.',
        'h1' => 'IGCSE Maths Tutors in Gurgaon (Core & Extended)',
        'lede' => 'Specialist IGCSE maths tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['ajay'],
    ],
    'icse-maths-tutor-gurgaon' => [
        'view' => 'icse-maths-tutor-gurgaon',
        'subject' => 'Mathematics',
        'board' => 'ICSE',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'maths-home-tutor-gurgaon',
        'label' => 'ICSE Maths',
        'title' => 'ICSE Maths Tutor in Gurgaon – Class 6 to 10 & ISC | NXTutors',
        'description' => 'ICSE maths home tutors in Gurgaon for Classes 6–10 and ISC 11–12: the CISCE syllabus, full working and board practice. Free demo class.',
        'h1' => 'ICSE Maths Tutors in Gurgaon (Classes 6–10) & ISC',
        'lede' => 'Specialist ICSE maths tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['abhinandan'],
    ],
    'igcse-physics-tutor-gurgaon' => [
        'view' => 'igcse-physics-tutor-gurgaon',
        'subject' => 'Physics',
        'board' => 'IGCSE',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'physics-home-tutor-gurgaon',
        'label' => 'IGCSE Physics',
        'title' => 'IGCSE Physics Tutor in Gurgaon – Core & Extended | NXTutors',
        'description' => 'Cambridge IGCSE Physics tutors in Gurgaon: Core and Extended, practical and alternative-to-practical papers, past-paper technique. Free demo class.',
        'h1' => 'IGCSE Physics Tutors in Gurgaon',
        'lede' => 'Specialist IGCSE physics tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['nxtutors'],
    ],
    'ib-physics-tutor-gurgaon' => [
        'view' => 'ib-physics-tutor-gurgaon',
        'subject' => 'Physics',
        'board' => 'IB',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'physics-home-tutor-gurgaon',
        'label' => 'IB Physics',
        'title' => 'IB Physics Tutor in Gurgaon – SL & HL, IA Guidance | NXTutors',
        'description' => 'IB DP Physics tutors in Gurgaon for SL and HL: concepts, data-based questions and Internal Assessment guidance. Free demo class.',
        'h1' => 'IB Physics Tutors in Gurgaon (SL & HL)',
        'lede' => 'Specialist IB physics tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['nxtutors'],
    ],
    'ib-igcse-chemistry-tutor-gurgaon' => [
        'view' => 'ib-igcse-chemistry-tutor-gurgaon',
        'subject' => 'Chemistry',
        'board' => 'IB',
        'city' => 'Gurugram',
        'city_slug' => 'gurugram',
        'parent' => 'chemistry-home-tutor-gurgaon',
        'label' => 'IB & IGCSE Chemistry',
        'title' => 'IB & IGCSE Chemistry Tutor in Gurgaon | NXTutors',
        'description' => 'IB DP (SL/HL) and Cambridge IGCSE Chemistry tutors in Gurgaon: concepts, practical skills, IA guidance and past papers. Free demo class.',
        'h1' => 'IB & IGCSE Chemistry Tutors in Gurgaon',
        'lede' => 'Specialist IB chemistry tutors across Gurugram who know the syllabus, the assessment and the schools that teach it.',
        'authors' => ['nxtutors'],
    ],
];
