@extends('super.layouts.app')
@section('title','Teacher Reviews')

@php use App\Support\ReviewOptions; @endphp

@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3">
  <h3 class="mb-0">Teacher Reviews</h3>
  <form method="GET" class="d-flex gap-2">
    <input type="hidden" name="tab" value="{{ $tab }}">
    <input type="search" name="q" value="{{ request('q') }}" class="form-control form-control-sm" placeholder="Name, email, text or tutor ID">
    <button class="btn btn-sm btn-outline-secondary">Search</button>
  </form>
</div>

@if (session('success'))
  <div class="alert alert-success">{{ session('success') }}</div>
@endif

<ul class="nav nav-tabs mb-3">
  @foreach($tabs as $key => $label)
    <li class="nav-item">
      <a class="nav-link {{ $tab === $key ? 'active' : '' }}" href="{{ route('super.teacher.review', ['tab' => $key]) }}">
        {{ $label }} <span class="badge {{ $key === 'pending' && ($counts[$key] ?? 0) ? 'bg-danger' : 'bg-secondary' }}">{{ $counts[$key] ?? 0 }}</span>
      </a>
    </li>
  @endforeach
</ul>

@if($tab === 'legacy')
  <div class="alert alert-warning small">
    These reviews existed before verified reviews were introduced. Many were generated by the tutor importer,
    so they are hidden from the site and from Google. Approve only the ones you know came from a real student or parent.
  </div>
@endif

@forelse($reviews as $row)
  <div class="card border-0 shadow-sm mb-3">
    <div class="card-body">
      <div class="d-flex flex-wrap gap-3">
        <div class="flex-shrink-0">
          @if($row->photoUrl())
            <a href="{{ $row->photoUrl() }}" target="_blank" rel="noopener">
              <img src="{{ $row->photoUrl() }}" alt="" width="64" height="64" class="rounded-circle object-fit-cover">
            </a>
          @else
            <div class="rounded-circle bg-light d-flex align-items-center justify-content-center fw-bold text-secondary" style="width:64px;height:64px;">{{ $row->initials() }}</div>
          @endif
        </div>

        <div class="flex-grow-1" style="min-width:260px;">
          <div class="d-flex flex-wrap align-items-center gap-2">
            <strong>{{ $row->name }}</strong>
            @if($row->email)
              <span class="text-muted small">{{ $row->email }}</span>
              @if($row->isEmailVerified())
                <span class="badge bg-success">Email verified</span>
              @else
                <span class="badge bg-warning text-dark">Email not verified</span>
              @endif
            @endif
            <span class="badge bg-warning text-dark">★ {{ $row->rating ?: '—' }}/5</span>
          </div>

          <div class="small text-muted mt-1">
            For <strong>{{ $row->user->name ?? 'Unknown tutor' }}</strong> ({{ $row->user_id }})
            @if($row->user && $row->user->profileUrl())
              · <a href="{{ $row->user->profileUrl() }}" target="_blank" rel="noopener">profile</a>
            @endif
            · {{ optional($row->submitted_at)->format('d M Y, H:i') ?? $row->date }}
          </div>

          @if($row->contextLine() || $row->duration)
            <div class="small mt-1">
              {{ $row->contextLine() }}
              @if($row->duration) · {{ ReviewOptions::label(ReviewOptions::DURATIONS, $row->duration) }} @endif
            </div>
          @endif

          <div class="small mt-1 text-muted">
            @foreach(ReviewOptions::SCORES as $field => $label)
              {{ $label }} {{ $row->{$field} ?: '—' }}@if(!$loop->last) · @endif
            @endforeach
          </div>

          @if($row->tagLabels())
            <div class="mt-2">
              @foreach($row->tagLabels() as $t)
                <span class="badge rounded-pill text-bg-light border">{{ $t }}</span>
              @endforeach
            </div>
          @endif

          <p class="mt-2 mb-0" style="white-space:pre-line;">{{ $row->message }}</p>

          @if($row->moderation === 'rejected' && $row->reject_reason)
            <div class="small text-danger mt-2">Rejected: {{ $row->reject_reason }}</div>
          @endif
          @if($row->moderated_at)
            <div class="small text-muted mt-1">Last moderated {{ $row->moderated_at->format('d M Y, H:i') }} by {{ $row->moderated_by }}</div>
          @endif
        </div>

        <div class="d-flex flex-column gap-2" style="min-width:180px;">
          @if($row->moderation !== 'approved')
            <form method="POST" action="{{ route('super.teacher.review.approve', $row->id) }}">
              @csrf
              <button class="btn btn-success btn-sm w-100">{{ $row->moderation === 'legacy' ? 'Restore & publish' : 'Approve & publish' }}</button>
            </form>
          @endif
          @if($row->moderation !== 'rejected')
            <form method="POST" action="{{ route('super.teacher.review.reject', $row->id) }}">
              @csrf
              <input type="text" name="reason" maxlength="255" class="form-control form-control-sm mb-1" placeholder="Reason (optional)">
              <button class="btn btn-outline-warning btn-sm w-100">{{ $row->moderation === 'approved' ? 'Unpublish' : 'Reject' }}</button>
            </form>
          @endif
          <form method="POST" action="{{ route('super.teacher.review.destroy', $row->id) }}"
                onsubmit="return confirm('Delete this review permanently?');">
            @csrf
            @method('DELETE')
            <button class="btn btn-outline-danger btn-sm w-100">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
@empty
  <div class="card border-0 shadow-sm"><div class="card-body text-muted">No reviews here.</div></div>
@endforelse

<div class="mt-3">{{ $reviews->links('pagination::bootstrap-5') }}</div>
@endsection
