<?php

declare(strict_types=1);

namespace App\Nxt\Dashboard\Models;

/**
 * A chapter-level practice test, from the bank or generated by the Test agent.
 */
class PracticeTest extends NxtModel
{
    protected $table = 'nxt_tests';

    protected $casts = [
        'questions' => 'array',
        'question_count' => 'integer',
    ];
}
